export * from './auth.service';
import { AuthService } from './auth.service';
export * from './brand.service';
import { BrandService } from './brand.service';
export * from './category.service';
import { CategoryService } from './category.service';
export * from './client.service';
import { ClientService } from './client.service';
export * from './commande.service';
import { CommandeService } from './commande.service';
export * from './ligneCommande.service';
import { LigneCommandeService } from './ligneCommande.service';
export * from './product.service';
import { ProductService } from './product.service';
export * from './tag.service';
import { TagService } from './tag.service';
export const APIS = [AuthService, BrandService, CategoryService, ClientService, CommandeService, LigneCommandeService, ProductService, TagService];
