/**
 * TutoApp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryDTO } from './categoryDTO';


export interface ProductDTO { 
    error?: string | null;
    hasError?: boolean | null;
    id?: number;
    name?: string | null;
    description?: string | null;
    picture?: string | null;
    price?: number;
    categoryID?: number | null;
    category?: CategoryDTO;
}

